### ISSUE TITLE
neue Option: Crosslinks auf verlinkter Seite nicht anwenden 

### ISSUE THREAD

**Issue by mrksgit** [Jako/Crosslinks#1]
Danke für das Extra. Ist schon in kleinem Umfang bei mir im Einsatz. Ist sehr nützlich, wenn man später noch Querverlinkungen einbauen möchte, ohne dann die (alten) Ressourcen nochmal zu bearbeiten. 

Möglicherweise wäre es sinnvoll, eine Option einzubauen, damit auf den verlinkten Crosslinks (nur auf das jeweilige Keyword bezogen) selbst keine Verlinkung erzeugt wird?

Beispiel: Ich habe eine Ressource (ID=5), in der es um "Crosslinks" geht. Ich erstelle ein Keyword im Extra, dass dann auf allen anderen Ressourcen zu einem Link nach ID=5 umgewandelt wird. Es wäre durchaus sinnvoll, dann in der Ressource selbst, in der es um Crosslinks geht - also ID=5 - auf die Erzeugung der Links des entsprechenden Keywords zu verzichten. Die Links führen ja dann nur auf die schon geöffnete Seite/Ressource.
Grüße

**Comment by Jako** [comment]
Kann man an dieser Stelle abfangen: https://github.com/Jako/Crosslinks/blob/master/core/components/crosslinks/model/crosslinks/crosslinks.class.php#L129-L134

Einfach diese Abfrage drum herum einbauen:
```
if ($link->get('resource') !== $this->modx->resource->get('id)) {
    <hier die Zeilen 129-134 einbauen>
} else {
    $result[$term->get('term')] = $term->get('term');
}
```

Ungetestet, aber sollte so funktionieren.

**Comment by mrksgit** [comment]
Danke. Ich sehe gerade, dass du bereits das fehlende Hochkomma hinzugefügt hast. Die ursprüngliche Anweisung im else hat bei mir zu einem Fehler geführt.
