### ISSUE TITLE
Error download 1.3.0 from modx.com

### ISSUE THREAD

**Issue by gravadesign** [Jako/Crosslinks#17]
Hi Jako

there is an error in the package download on the [modx.com site ](https://modx.com/extras/package/crosslinks)

![Schermata 2022-04-29 alle 11 39 57](https://user-images.githubusercontent.com/5929863/165921141-a45e0d27-25d7-4d35-b62c-ac6ea098cd58.png)

Package Management:
![Schermata 2022-04-29 alle 11 49 27](https://user-images.githubusercontent.com/5929863/165922512-a838ba1a-5677-4929-96c2-80f58ff1452c.png)

**Comment by Jako** [comment]
I have reuploaded the package file to MODX extras.

**Comment by gravadesign** [comment]
Now it's ok
