### ISSUE TITLE
neue Option: nur die ersten n-Vorkommen beachten bzw. nur den ersten Treffer verlinken

### ISSUE THREAD

**Issue by mrksgit** [Jako/Crosslinks#2]
Wäre es sinnvoll eine (einstellbare) Option mit einzubauen, die dazu führt, nur die ersten n-Vorkommen  des Schlagwortes in einer Ressource auch zu verlinken? Wenn das Schlagwort z.B. 10 Mal in einem Text vorkommt, ist es ja nicht weiterführend auch alle 10 Treffer zu verlinken. 

Beispiel: 0 steht für deaktiviert (alle Treffer werden verlinkt), und eine beliebige ganze Zahl n steht für die Verlinkung der ersten n-Treffer. Falls das zu sehr auf die Performance schlagen sollte, wäre dann auch denkbar, dass man das als Aus/An-Option einbaut (0: alle Treffer/ 1: nur der erste Treffer o.ä.)?
Grüße

**Comment by Jako** [comment]
Ist in Version 1.2.1 eingebaut: https://github.com/Jako/Crosslinks/blob/1.2.1/_packages/crosslinks-1.2.1-pl.transport.zip
